### ISSUE TITLE
Installation either unclear or very intrusive

### ISSUE THREAD

**Issue by Morisander** [BeTechnologyCo/Web3Library#1]
good day my friend, i just tried to install your plugin several times (always tried it on a fresh project, installed the needed json plugin, and copied the content of your repository into the root of the project.

i do not understand, why there is this much of content needed, especially the project settings?

the other problem is, that as soon as i install the library, it spits out around 40 warning about several problems in the scripts, here a few of them:
Assets\web3\Sample\Scripts\Sample.cs(41,16): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
Assets\web3\Plugins\Web3Unity\WalletConnect\WalletConnectSharp.Core\WalletConnectProvider.cs(16,58): warning CS0067: The event 'WalletConnectProvider.OnProviderConnect' is never used
Assets\web3\Plugins\Web3Unity\WalletConnect\WalletConnectSharp.NEthereum\WalletConnectNEthereumExtensions.cs(92,26): warning CS0618: 'WalletConnectNEthereumExtensions.CreateProvider(WalletConnectSession, Uri, AuthenticationHeaderValue)' is obsolete: 'Use BuildWeb3(url).AsUnmanagedAccount() instead. Will be removed in v2'

**Comment by youtpout** [comment]
Hello,
just import the unitypackage in the lastest release
https://github.com/BeTechnologyCo/Web3Library/releases

The sample folder demonstrate how to use the library, if you don't need it, remove it, just keep plugins and editor folder

**Comment by Morisander** [comment]
okay, thanks, i tried it now, and deleting the sample folder also eliminated all showed issues. but maybe i should tell you, that the samples folder seems to inherit 41 warnings and even a compiler error:)

**Comment by youtpout** [comment]
Hello,
I know for the warning but I don’t have compilation error.
Which version of Unity do you use ?
Which export platform do you choose ?
